# SOURCE: https://cloud.google.com/kubernetes-engine/docs/tutorials/guestbook
apiVersion: v1
kind: Service
metadata:
  name: backend-apachelivy
  labels:
    app: apachelivy
    tier: backend
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  # type: LoadBalancer
  type: NodePort
  ports:
    # the port that this service should serve on
  - port: 8080
    protocol: TCP
    port: 8998
    protocol: TCP
  selector:
    app: apachelivy
    tier: backend-apachelivy