apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
        app: nginx
        tier: proxy
  template:
    metadata:
      labels:
        app: nginx
        tier: proxy
    spec:
      containers:
      - name: proxy-nginx
        image: 11223456786/numtra_platform_2.0:numtranginx_2.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        - containerPort: 443
#        resources:
#          requests:
#            cpu: 100m
#            memory: 100Mi
      imagePullSecrets:
      - name: regcred