# SOURCE: https://cloud.google.com/kubernetes-engine/docs/tutorials/guestbook
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-mongodb
spec:
  replicas: 2
  selector:
    matchLabels:
        app: mongodb
        tier: proxy
  template:
    metadata:
      labels:
        app: mongodb
        tier: proxy
    spec:
      containers:
      - name: proxy-mongodb
        image: 11223456786/numtra_platform_2.0:numtramongodb_2.0
        imagePullPolicy: IfNotPresent
#        resources:
#          requests:
#            cpu: 100m
#            memory: 100Mi
        ports:
        - containerPort: 80
          protocol: TCP
        - containerPort: 27012
          protocol: TCP
        imagePullSecrets:
          - name: regcred